@EFCore.RestApi_HostAddress = https://localhost:7065
@contentType = application/json

### Company
GET {{EFCore.RestApi_HostAddress}}/api/Company?count=4&last=10

###
GET {{EFCore.RestApi_HostAddress}}/api/Company/43

### Person
GET {{EFCore.RestApi_HostAddress}}/api/Person

### Movie
GET {{EFCore.RestApi_HostAddress}}/api/Movie

### Superhero
GET {{EFCore.RestApi_HostAddress}}/api/Superhero?count=4&last=20

###
GET {{EFCore.RestApi_HostAddress}}/api/superhero/3

###
PUT {{EFCore.RestApi_HostAddress}}/api/superhero/3
Content-Type: {{contentType}}

{
  "id": 23,
  "name": "Daredevil",
  "firstName": "Matt",
  "lastName": "Murdock",
  "publisher": 1
}

### ISO Country
GET {{EFCore.RestApi_HostAddress}}/api/ISOCountry

### US State
GET {{EFCore.RestApi_HostAddress}}/api/USState

### US Zip code
GET {{EFCore.RestApi_HostAddress}}/api/USZipCode

###
GET {{EFCore.RestApi_HostAddress}}/api/USZipCode/32937
