@HostAddress = https://localhost:7065
@contentType = application/json

### ISO Country
GET {{HostAddress}}/api/ISOCountry

### Province
GET {{HostAddress}}/api/Province

###
GET {{HostAddress}}/api/Postcode/32937

### Company
GET {{HostAddress}}/api/Company?count=4&last=10

###
GET {{HostAddress}}/api/Company/43

### Person
GET {{HostAddress}}/api/Person

### Movie
GET {{HostAddress}}/api/Movie

### Superhero
GET {{HostAddress}}/api/Superhero?count=4&last=20

###
GET {{HostAddress}}/api/superhero/3

### Create New
POST {{HostAddress}}/api/superhero
Content-Type: {{contentType}}

{
  "name": "KevKogs",
  "firstName": "Kevin",
  "lastName": "Heath",
  "publisher": "Marvel"
}

### Update
PUT {{HostAddress}}/api/superhero/xx
Content-Type: {{contentType}}

{
  "name": "KevKogs",
  "firstName": "Kevin",
  "lastName": "Heath",
  "place": "Orlando",
  "publisher": "Marvel"
}

### Delete
DELETE {{HostAddress}}/api/superhero/xx
