# This workflow will build a .NET solution or project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  workflow_dispatch:
    inputs:
      run-name:
        description: A name for the run
        type: string
        required: true
      runs-on:
        description: The runner type to use
        type: choice
        options: 
        - ubuntu-latest
        - windows-latest
        default: ubuntu-latest
      project-folder:
        description: Folder containing the project
        type: string
        default: .

run-name: ${{ inputs.run-name }}

jobs:

  build:
    name: Build .NET
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}

    steps:

    # Must be run first as working directory may not be the root
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
