name: Log Environment

on:
  workflow_dispatch:
    inputs:
      run-name:
        description: A name for the run
        type: string
        required: true
      runs-on:
        description: The runner type to use
        type: choice
        options: 
        - ubuntu-latest
        - windows-latest
        default: ubuntu-latest
      project-folder:
        description: Folder containing the solution
        type: string
        default: .

run-name: ${{ inputs.run-name }}

jobs:

  variables:
    name: Variables
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Linux
        if: runner.os != 'Windows'
        env:
          GITHUB_ACTIONS: ${{ toJson(github) }}
        run: |
          echo "Branch name is ${{ steps.branch-name.outputs.current_branch }}"
          echo "Running on ${{ inputs.runs-on }}"
          echo "Workspace is ${{ github.workspace }}"
          echo "Project folder is ${{ inputs.project-folder }}"
          echo "GITHUB_ACTIONS is $GITHUB_ACTIONS"

      - name: Windows
        if: runner.os == 'Windows'
        run: |
          echo "Branch name is ${{ steps.branch-name.outputs.current_branch }}"
          echo "Running on ${{ inputs.runs-on }}"
          echo "Workspace is ${{ github.workspace }}"
          echo "Project folder is ${{ inputs.project-folder }}"
          echo "GITHUB_ACTIONS is $env:GITHUB_ACTIONS"
